name: "Deploy frontend production"

on:
  push:
    branches:
      - "main"

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy frontend production"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: "Deploy to Vercel Prod"
        id: "prod_deploy"
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
