# name: Preview deploy
# on:
#   pull_request:
#     branches:
#       - main
#   pull_request_target:
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: amondnet/vercel-action@v20
#         id: vercel-action
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           github-token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
#           vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
#           vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
#       - name: preview-url
#         run: |
#           echo ${{ steps.vercel-action.outputs.preview-url }}
